server:
  port: 8401
spring:
  application:
    name: sentinelDemo
  cloud:
    nacos:
      discovery:
        server-addr: 81.69.193.138:8848
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，键入被占用会自动从8719+1，直到找到未被占用的端口
        port: 8719
      web-context-unify: false
      datasource:
        nacos:
          nacos:
            serverAddr: 81.69.193.138:8848
            groupId: DEFAULT_GROUP
            dataID:  order-sentinel.json
            ruleType: flow
