server:
  port: 9003
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 81.69.193.138:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'